apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ygwm7iddf-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ygwm7iddf-java-springboot-gitops